"""Added practiceId field and deleted isIdeleted field

Revision ID: 8070db793370
Revises: aedb0652ca0e
Create Date: 2025-10-20 09:56:08.109331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8070db793370'
down_revision: Union[str, None] = 'aedb0652ca0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('practice_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_interactions_practice_id'), 'interactions', ['practice_id'], unique=False)
    op.drop_column('interactions', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_interactions_practice_id'), table_name='interactions')
    op.drop_column('interactions', 'practice_id')
    # ### end Alembic commands ###
