"""Added is_deleted column for soft delete

Revision ID: d20984f1e050
Revises: 4c2977af2170
Create Date: 2025-07-09 13:59:37.635197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20984f1e050'
down_revision: Union[str, None] = '4c2977af2170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'is_deleted')
    # ### end Alembic commands ###
