"""Change state to states array in Interaction model

Revision ID: d692d0e66443
Revises: d20984f1e050
Create Date: 2025-09-05 13:10:36.910399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd692d0e66443'
down_revision: Union[str, None] = 'd20984f1e050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('states', postgresql.JSONB(astext_type=sa.Text()), server_default='["IDLE"]', nullable=False))
    op.drop_column('interactions', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('interactions', 'states')
    # ### end Alembic commands ###
