"""Adding interaction data column to the interactions table

Revision ID: ec718cc463da
Revises: b94c22e74ef6
Create Date: 2025-06-17 15:46:14.432909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec718cc463da'
down_revision: Union[str, None] = 'b94c22e74ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('interaction_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'interaction_data')
    # ### end Alembic commands ###
