import enum


class ChatflowState(str, enum.Enum):
    """
    Defines the possible states in the example flow.
    """
    CLASSIFYING_INTENT= "CLASSIFYING_INTENT"
    ASK_USER_DATA="ASK_USER_DATA"
    BOOK_CALL_OFFER_ACCEPTED="BOOK_CALL_OFFER_ACCEPTED"
    BOOK_CALL_OFFER_DECLINED="BOOK_CALL_OFFER_DECLINED"
    CUSTOMER_ACKNOWLEDGES_RESPONSE= "CUSTOMER_ACKNOWLEDGES_RESPONSE"
    IDLE="IDLE"
    INTENT_FRUSTRATED_CUSTOMER="INTENT_FRUSTRATED_CUSTOMER"
    INTENT_GENERAL_FAQ_QUESTION="INTENT_GENERAL_FAQ_QUESTION"
    INTENT_GOODBYE = "INTENT_GOODBYE"
    INTENT_OUT_OF_SCOPE_QUESTION="INTENT_OUT_OF_SCOPE_QUESTION"
    OFFER_BOOK_CALL="OFFER_BOOK_CALL"
    REPLY_FROM_EMBEDDINGS="REPLY_FROM_EMBEDDINGS"
    AWAITING_NEW_MESSAGE= "AWAITING_NEW_MESSAGE"
    AWAITING_BOOK_CALL_OFFER_RESPONSE="AWAITING_BOOK_CALL_OFFER_RESPONSE"
    FINAL="FINAL"
    INTENT_QUESTION_BOT_CREATION="INTENT_QUESTION_BOT_CREATION"
    INTENT_QUESTION_PRICING="INTENT_QUESTION_PRICING"
    INVITE_CREATE_ACCOUNT="INVITE_CREATE_ACCOUNT"
